/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { OfficeWhereUniqueInput } from "../../office/base/OfficeWhereUniqueInput";
import { Type } from "class-transformer";
import { QueueCreateNestedManyWithoutServicesInput } from "./QueueCreateNestedManyWithoutServicesInput";
import { StaffCreateNestedManyWithoutServicesInput } from "./StaffCreateNestedManyWithoutServicesInput";

@InputType()
class ServiceCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => OfficeWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => OfficeWhereUniqueInput)
  @IsOptional()
  @Field(() => OfficeWhereUniqueInput, {
    nullable: true,
  })
  office?: OfficeWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => QueueCreateNestedManyWithoutServicesInput,
  })
  @ValidateNested()
  @Type(() => QueueCreateNestedManyWithoutServicesInput)
  @IsOptional()
  @Field(() => QueueCreateNestedManyWithoutServicesInput, {
    nullable: true,
  })
  queues?: QueueCreateNestedManyWithoutServicesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  serviceCode?: string | null;

  @ApiProperty({
    required: false,
    type: () => StaffCreateNestedManyWithoutServicesInput,
  })
  @ValidateNested()
  @Type(() => StaffCreateNestedManyWithoutServicesInput)
  @IsOptional()
  @Field(() => StaffCreateNestedManyWithoutServicesInput, {
    nullable: true,
  })
  staffItems?: StaffCreateNestedManyWithoutServicesInput;
}

export { ServiceCreateInput as ServiceCreateInput };
